In [168]:
import pandas as pd

# df = pd.read_pickle("my_data.pkl")
df = pd.read_pickle("my_data_duplicated.pkl")

In [169]:
df.head()

,price,property_type,num_bed,num_bath,num_reception,msoa,ethnicity_asian,ethnicity_black,ethnicity_mixed,ethnicity_white,...,travel_time_>30,travel_time_offshore,travel_method_wfh,travel_method_public,travel_method_cycle,travel_method_rail,travel_method_driving,travel_method_foot,travel_method_other,date
0,599950.0,Semi-detached house,5,2,2,E02003784,3.530171,0.586950,2.077557,93.147617,...,3.8,10.9,43.5,1.7,4.1,0.6,47.4,2.2,0.6,2019-03-31
1,315000.0,Semi-detached house,2,0,0,E02003780,7.773759,2.118440,3.946910,85.057092,...,2.8,9.1,46.9,3.4,11.4,0.4,32.8,4.4,0.7,2019-03-31
2,275000.0,Terraced house,2,1,1,E02003724,10.888131,2.889416,4.740059,78.964293,...,3.4,10.6,36.9,4.9,19.6,0.7,28.9,8.0,0.9,2018-03-14
3,500000.0,Semi-detached house,3,2,2,E02003729,20.943260,2.369090,4.449682,67.928793,...,3.2,9.1,37.2,6.6,15.9,1.0,32.6,5.9,0.9,2018-06-01
4,270000.0,End terrace house,4,1,1,E02003737,1.343225,1.388279,2.286450,94.115225,...,4.6,15.2,26.3,1.2,2.7,1.0,63.5,4.3,0.8,2018-09-19

**Shannon entropy**

$$
H = -\sum_{i=1}^K p_i \log(p_i)
$$

If all groups are equally represented, $p_i = \frac{1}{K}$, $H = -K \cdot \frac{1}{K} \log \frac{1}{K} = \log K$.

So people often use a normalized version
$$
H = \frac{-\sum_{i=1}^K p_i \log(p_i)}{\log K}
$$
which gives a value between 0 and 1
- $H=0$: no diversity
- $H=1$: max diversity

**Simpson diversity index / Gini-Simpson index**

Concentration measure:
$$
\lambda = \sum_{i=1}^K p_i^2
$$
Higher when one group dominates.

Diversity measure:
$$
D = 1 - \sum_{i=1}^K p_i^2
$$

Interpretation: the probablity that two randomly selected people from the region belong to different groups (higher when diverse)

maximum value: $1 - \frac{1}{K}$

normalized version:
$$
D = \frac{1 - \sum_{i=1}^K p_i^2}{1 - \frac{1}{K}}
$$

Normalisation refers to normalizing across number of classes

# Shannon

In [170]:
ethnicity_cols = ["ethnicity_asian", "ethnicity_black", "ethnicity_mixed", "ethnicity_white", "ethnicity_other"]
age_cols = ["age_minor", "age_adult", "age_elder"]
edu_cols = ["education_low", "education_medium", "education_high", "education_other"]
travel_time_cols = ["travel_time_0", "travel_time_0-5", "travel_time_5-30", "travel_time_>30", "travel_time_offshore"]
travel_method_cols = ["travel_method_wfh", "travel_method_public", "travel_method_cycle", "travel_method_rail", "travel_method_driving", "travel_method_foot", "travel_method_other"]

In [171]:
import numpy as np

def shannon(p):
    K = p.shape[1]
    return (
            -np.where(
            p>0,
            p * np.log(p),
            0
        ).sum(axis=1)
    ) / np.log(K)

In [172]:
df["ethnicity_shannon"] = shannon(df[ethnicity_cols] / 100)
df["age_shannon"] = shannon(df[age_cols] / 100)
df["edu_shannon"] = shannon(df[edu_cols] / 100)
df["travel_time_shannon"] = shannon(df[travel_time_cols] / 100)
df["travel_method_shannon"] = shannon(df[travel_method_cols] / 100)

# Simpson

In [173]:
def simpson(p):
    K = p.shape[1]
    return (1 - (p ** 2).sum(axis=1)) / (1 - 1/K)

In [174]:
df["ethnicity_simpson"] = simpson(df[ethnicity_cols] / 100)
df["age_simpson"] = simpson(df[age_cols] / 100)
df["edu_simpson"] = simpson(df[edu_cols] / 100)
df["travel_time_simpson"] = simpson(df[travel_time_cols] / 100)
df["travel_method_simpson"] = simpson(df[travel_method_cols] / 100)

In [175]:
df.head()

,price,property_type,num_bed,num_bath,num_reception,msoa,ethnicity_asian,ethnicity_black,ethnicity_mixed,ethnicity_white,...,ethnicity_shannon,age_shannon,edu_shannon,travel_time_shannon,travel_method_shannon,ethnicity_simpson,age_simpson,edu_simpson,travel_time_simpson,travel_method_simpson
0,599950.0,Semi-detached house,5,2,2,E02003784,3.530171,0.586950,2.077557,93.147617,...,0.203493,0.951052,0.787893,0.796233,0.545529,0.163247,0.944791,0.837057,0.838436,0.680835
1,315000.0,Semi-detached house,2,0,0,E02003780,7.773759,2.118440,3.946910,85.057092,...,0.368991,0.922734,0.784199,0.822436,0.656516,0.335457,0.911679,0.824865,0.857325,0.765686
2,275000.0,Terraced house,2,1,1,E02003724,10.888131,2.889416,4.740059,78.964293,...,0.476207,0.822466,0.796521,0.811941,0.756971,0.451143,0.790546,0.842715,0.853729,0.855133
3,500000.0,Semi-detached house,3,2,2,E02003729,20.943260,2.369090,4.449682,67.928793,...,0.592411,0.896516,0.791656,0.803099,0.750527,0.612850,0.877000,0.830648,0.848869,0.842381
4,270000.0,End terrace house,4,1,1,E02003737,1.343225,1.388279,2.286450,94.115225,...,0.187974,0.924703,0.829951,0.884908,0.519146,0.141573,0.910456,0.874653,0.910432,0.612173

In [176]:
df.to_pickle("my_data_diversity.pkl")